version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
     - "3000"
     - "8000"
    command: "npm run production"
    ports:
      - 0.0.0.0:3000:3000/tcp
      - 0.0.0.0:8000:8000/tcp
