version: "2"
services:
  botapp:
    container_name: botapp
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - ./.env
    volumes:
      - ./:/usr/src/app
    expose:
     - "3000"
     - "8000"
    command: "npm run ${NODE_ENV}"
    ports:
      - 0.0.0.0:3000:3000/tcp
      - 0.0.0.0:8000:8000/tcp
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes_from:
      - mongodata

  mongodata:
    container_name: mongodata
    image: tianon/true
    volumes:
      - /data/db
